### ISSUE TITLE
[Feature Request] Enforce type safety 

### ISSUE THREAD

**Issue by pongloongyeat** [heickjack619lok/dumbdumb_flutter#6]
This project/repository lacks an analysis_options.yaml file for linting. I would recommend that we add this (currently, we're facing quite a lot of type-safety issues for Evetag, which is based on this template). A sample analysis_options.yaml file:

```yaml
include: package:very_good_analysis/analysis_options.2.4.0.yaml
analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  errors:
    missing_enum_constant_in_switch: error
linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    no_default_cases: false
    avoid_catching_errors: false
    use_setters_to_change_properties: false
```
